# Generated by Django 2.1.7 on 2019-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='', max_length=30, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modify_time',
            field=models.DateField(default='2015-5-15', verbose_name='modify_time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='release_time',
            field=models.DateField(verbose_name='release_time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='post.tag'),
        ),
    ]
