# Generated by Django 2.1.7 on 2019-04-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release_time',
            field=models.DateField(verbose_name='release_time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
