# Generated by Django 2.1.7 on 2019-04-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190424_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='default',
            field=models.TextField(default='default', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default=' ', max_length=30, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
