# Generated by Django 2.1.7 on 2019-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190526_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='title')),
                ('path', models.ImageField(default='upload/default.jpg', upload_to='upload/%Y/%m', verbose_name='image')),
                ('referencePost', models.ManyToManyField(to='post.post')),
            ],
        ),
    ]
