# Generated by Django 2.1.7 on 2019-05-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='referencePost',
            new_name='referencePosts',
        ),
    ]
