# Generated by Django 2.2 on 2019-05-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190424_1746'),
        ('post', '0002_blogimage'),
    ]

    operations = [
    ]
